apiVersion: v1
kind: ServiceAccount
metadata:
  name: standard-sa
  namespace: #{namespace}#
  annotations:
    azure.workload.identity/client-id: #{standard_identity_resource_clientId}#
  labels:
    azure.workload.identity/use: "true"