trigger: 
  branches: 
    include:
    - main
  paths:
    include:
    - FrontDoor/*

extends:
  template: ../Templates/terraform-frontdoor.yaml
  parameters:
    folder: FrontDoor
    deploy_yaml: false