trigger: 
  branches: 
    include:
    - main
  paths:
    include:
    - EnvironmentResources/*

extends:
  template: ../Templates/terraform-environment.yaml
  parameters:
    folder: EnvironmentResources
    service_name: envresources